before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - jdyer@spreecommerce.com
    - peter@pero-ict.nl
  irc: "irc.freenode.org#spree"
branches:
  only:
    - master
    - 1-0-stable
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
